[package]
name = "chrono-english"
version = "0.1.0"
authors = ["steve donovan <steve.j.donovan@gmail.com>"]

[dependencies]
chrono = "0.4"
scanlex = "0.1.2"
time = "0.1"

[dev-dependencies]
lapp = "0.3"

